---
# tasks file for kubernetes-common

- name: Set SELinux permissive
  selinux: 
    policy: targeted 
    state: permissive

- name: Install pkgs {{ packages }}
  yum: 
    name: "{{ packages }}"
    state: present 
  vars:
    packages:
      - deltarpm
      - epel-release
      - wget
      - ntp
      #- jq
      - git
      - net-tools
      - bind-utils
      #- moreutils
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2